# Conexão com o MySQL
spring.datasource.url=jdbc:mysql://zelaproject-guilhermeh-e82d.a.aivencloud.com:20460/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=Coloca aqui
# Driver e Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
