version: '3.8'

services:
  mysql-zela:
    image: mysql:8.0
    container_name: zela_db_container
    restart: always
    environment:
      MYSQL_DATABASE: zela_db
      MYSQL_ROOT_PASSWORD: G3D3d5F7gh13100%
    ports:
      - "3307:3306"
    volumes:
      - zela_mysql_data:/var/lib/mysql

volumes:
  zela_mysql_data:

